# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 40636c13b546faec143ff252f633580df549234f25fda84f349548e7b536f82c2e0477c0324221ba696f819c39d3d29a0414d9a8b739a757fb3d03b8785bc3a1

test:
  secret_key_base: 3de2b972a83a1b4305a3f2a690b717de88f62ccaf2ce2a54ee961b5ababfb02c215146e729698982a0cbb054cbd660149dd20ec5298aa51710a525263888f583

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
